# Generated by Django 5.1.6 on 2025-02-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
